dist: xenial
services: docker

language: go
go:
  - "1.12.x"

before_script:
  - export VPP_IMG="ligato/vpp-base:latest"
  - docker pull $VPP_IMG

script:
  - make test
  - make build
  - make examples
  - make gen-binapi-docker

notifications:
  slack:
    rooms:
      - ligato:QNOK2VgHH6k40T8nQxmSgRmo
    on_success: change
    on_failure: always
